kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: slack-webhook
          match:
            severity: slack
          group:wait: 10s
          repeat_interval: 1m      
    receivers:
    - name: alert-emailer
      email_configs:
      - to: haelwazery@gmail.com
        send_resolved: false
        from: from-email@email.com
        smarthost: smtp.eample.com:25
        require_tls: false
    - name: slack-webhook
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: this-is-for-the-alerts
